/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 24-Jun-2018 17:13:20 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_EmployeeDepartment_Department]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [EmployeeDepartment] DROP CONSTRAINT [FK_EmployeeDepartment_Department]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_EmployeeDepartment_Employee]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [EmployeeDepartment] DROP CONSTRAINT [FK_EmployeeDepartment_Employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Salary_Employee]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Salary] DROP CONSTRAINT [FK_Salary_Employee]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Department]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Department]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Employee]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[EmployeeDepartment]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [EmployeeDepartment]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Salary]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Salary]
GO

/* Create Tables */

CREATE TABLE [Department]
(
	[Id] int NOT NULL,
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [Employee]
(
	[Id] int NOT NULL,
	[FirstName] varchar(50) NOT NULL,
	[LastName] varchar(50) NOT NULL,
	[EmployeeNumber] varchar(50) NOT NULL,
	[JobTitle] varchar(50) NOT NULL,
	[ContactNumber] varchar(50) NOT NULL,
	[Gender] int NOT NULL,
	[HireDate] datetime NOT NULL
)
GO

CREATE TABLE [EmployeeDepartment]
(
	[EmployeeId] int NOT NULL,
	[DepartmentId] int NOT NULL,
	[StartDate] datetime NOT NULL,
	[EndDate] datetime NOT NULL,
	[Id] int NULL
)
GO

CREATE TABLE [Salary]
(
	[Id] int NOT NULL,
	[Amount] decimal(18) NOT NULL,
	[StartDate] datetime NOT NULL,
	[EndDate] datetime NOT NULL,
	[EmployeeId] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Department] 
 ADD CONSTRAINT [PK_Department]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Employee] 
 ADD CONSTRAINT [PK_Employee]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_EmployeeDepartment_Department] 
 ON [EmployeeDepartment] ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_EmployeeDepartment_Employee] 
 ON [EmployeeDepartment] ([Id] ASC)
GO

ALTER TABLE [Salary] 
 ADD CONSTRAINT [PK_Salary]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Salary_Employee] 
 ON [Salary] ([Id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [EmployeeDepartment] ADD CONSTRAINT [FK_EmployeeDepartment_Department]
	FOREIGN KEY ([Id]) REFERENCES [Department] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [EmployeeDepartment] ADD CONSTRAINT [FK_EmployeeDepartment_Employee]
	FOREIGN KEY ([Id]) REFERENCES [Employee] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Salary] ADD CONSTRAINT [FK_Salary_Employee]
	FOREIGN KEY ([Id]) REFERENCES [Employee] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
